name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Remove the QEMU setup as it's not needed for basic Docker Compose

      # Install Docker Compose V2
      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      # Verify Docker Compose installation
      - name: Verify Docker Compose Installation
        run: docker compose version

      - name: Copy .env.example to .env
        run: cp /.env.example /.env

      - name: Run integration script
        working-directory: ./
        run: |
          docker compose up -d
          npm run test:integration
          docker compose down
